### ISSUE TITLE
Unable to run .net core console app using sixeyed/coreclr-base

### ISSUE THREAD

**Issue by Parth6288** [sixeyed/dockers#3]
Hi,
I am trying to run my .net core console application on container in CentOS as host using the below link :
https://blog.sixeyed.com/running-net-core-apps-in-a-linux-container/
However i am getting error **container_linux.go:247: starting container process caused "exec: \"dotnet\": executable file not found in $PATH"
/usr/bin/docker-current: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"dotnet\\\": executable file not found in $PATH\"\n".**

Below is my Dockerfile content:
FROM sixeyed/coreclr-base
ENV PATH /root/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta8-15618/bin:$PATH
WORKDIR /app
COPY <src> /app
ENTRYPOINT ["dotnet", "<name>.dll"]

**Comment by sixeyed** [comment]
Hi - this example is pretty old. The .NET Core runtime has moved on a lot since that blog post, there's no DNX any more and Microsoft keep their own base images up to date on Docker Hub. The [.NET Core tutorial](https://docs.docker.com/engine/examples/dotnetcore/) is a better resource to use.

**Comment by Parth6288** [comment]
Thanks Elton. I did tried using microsoft/aspnetcore:latest image and running the compiled app gives me below error.
**Failed to initialize CoreCLR, HRESULT: 0x80131500**

Here's the code that i am trying inside the container : **root@edcb7a48635d:/# dotnet /path/appname.dll**
